//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Threading;

namespace WindowsPresentationFramework.Properties
{
    public partial class Settings : ApplicationSettingsBase
    {
        private static Settings m_Value;

        private static object m_SyncObject = new object();

        public static Settings Value
        {
            get
            {
                if ((m_Value == null))
                {
                    Monitor.Enter(m_SyncObject);
                    if ((m_Value == null))
                    {
                        try
                        {
                            m_Value = new Settings();
                        }
                        finally
                        {
                            Monitor.Exit(m_SyncObject);
                        }
                    }
                }
                return m_Value;
            }
        }
    }
}